src/core/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path("^admin/", admin.site.urls),
    re_path("", include("university.urls.r_main", namespace="university")),
]

# media and static file url conf
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/university/models/ac_year.py
from django.db import models
from django.urls import reverse


class AcademicYear(models.Model):
    """Defines the university academic year in a string format"""

    name = models.CharField(
        max_length=9, null=False, unique=True, help_text="Eg. 2023/24 or 2023/2024"
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("university:academic_years:detail", kwargs={"pk": self.pk})

    class Meta:
        db_table = "university_academic_year"
        ordering = ["name", "id"]

src/university/models/intake_class.py
from django.db import models
from django.urls import reverse

from .ac_year import AcademicYear


class IntakeClass(models.Model):
    academic_year = models.ForeignKey(to=AcademicYear, on_delete=models.CASCADE)
    class_code = models.CharField(max_length=20, unique=True)

    def __str__(self) -> str:
        return self.class_code

    def get_absolute_url(self):
        return reverse("university:intake_classes:detail", kwargs={"class_pk": self.pk})

    class Meta:
        ordering = ["class_code"]
        db_table = "university_intake_class"


class IntakeStream(models.Model):
    """Signify the divided portion of an intake class"""

    intake_class = models.ForeignKey(
        to=IntakeClass, on_delete=models.CASCADE, related_name="streams"
    )
    stream_code = models.CharField(max_length=20, unique=True)

    def __str__(self) -> str:
        return self.stream_code

    def get_absolute_url(self):
        return reverse(
            "university:intake_classes:streams:detail",
            kwargs={"class_pk": self.intake_class.pk, "stream_pk": self.pk},
        )

    class Meta:
        ordering = ["stream_code"]
        db_table = "university_intake_stream"

src/university/models/lecturer.py
from django.db import models
from django.urls import reverse


class Lecturer(models.Model):
    full_name = models.CharField(max_length=60)
    email = models.EmailField(max_length=255, unique=True)
    avatar = models.ImageField(max_length=275, upload_to="lecturers/")

    def __str__(self) -> str:
        return self.full_name

    def get_absolute_url(self):
        return reverse("university:lecturers:detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["full_name"]

src/university/models/module.py
from django.db import models
from django.urls import reverse


class Module(models.Model):
    title = models.CharField(max_length=200, unique=True)
    code = models.CharField(max_length=12, unique=True)

    def __str__(self) -> str:
        return f"{self.title} ({ self.code })"

    def get_absolute_url(self):
        return reverse("university:modules:detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["title", "code", "id"]

src/university/models/timetable.py
from django.db import models
from django.urls import reverse

from .intake_class import IntakeStream
from .ac_year import AcademicYear


class Timetable(models.Model):
    """
    No more than one timetable should be created for one intake stream in a semester of the
    same academic year.
    """

    SEM1 = 1
    SEM2 = 2

    SEMESTER_CHOICES = (("1", "Sem 1"), ("2", "Sem 2"))

    title = models.CharField(max_length=255, default="", editable=False)
    intake_stream = models.ForeignKey(
        to=IntakeStream, on_delete=models.SET_NULL, null=True
    )
    academic_year = models.ForeignKey(
        to=AcademicYear, on_delete=models.SET_NULL, null=True
    )
    semester = models.CharField(
        max_length=1,
        choices=SEMESTER_CHOICES,
        default="1",
        help_text="Each academic year has a maximum of 2 semesters, defaults to 1",
    )

    def get_absolute_url(self):
        return reverse("university:timetables:detail", kwargs={"timetable_pk": self.pk})

    def __str__(self) -> str:
        return f"{self.academic_year.name}: {self.intake_stream}"

    def save(self, *args, **kwargs):
        # set title
        self.title = f"{self.intake_stream.stream_code} - {self.academic_year.name} (Sem {self.semester})"
        return super().save(*args, **kwargs)

    class Meta:
        unique_together = ["semester", "intake_stream", "academic_year"]

src/university/forms/f_academic_year.py
from shared.forms import StyledModelForm

from ..models import AcademicYear


class AcademicYearForm(StyledModelForm):
    class Meta:
        model = AcademicYear
        fields = ["name"]

src/university/forms/f_intake_class.py
from shared.forms import StyledModelForm

from ..models import IntakeClass


class IntakeClassForm(StyledModelForm):
    class Meta:
        model = IntakeClass
        fields = ["academic_year", "class_code"]

src/university/forms/f_intake_stream.py
from typing import Any
from shared.forms import StyledModelForm

from ..models import IntakeStream


class IntakeStreamForm(StyledModelForm):
    class Meta:
        model = IntakeStream
        fields = ["stream_code"]

src/university/forms/f_lecturer.py
from shared.forms import StyledModelForm

from ..models import Lecturer


class LecturerForm(StyledModelForm):
    class Meta:
        model = Lecturer
        fields = ["full_name", "email", "avatar"]

src/university/forms/f_module.py
from shared.forms import StyledModelForm

from ..models import Module


class ModuleForm(StyledModelForm):
    class Meta:
        model = Module
        fields = ["title", "code"]

src/university/forms/f_session.py
from shared.forms import StyledModelForm

from ..models import Session


class SessionForm(StyledModelForm):
    class Meta:
        model = Session
        exclude = ["timetable"]

src/university/forms/f_timetable.py
from shared.forms import StyledModelForm

from ..models import Timetable


class TimetableForm(StyledModelForm):
    class Meta:
        model = Timetable
        fields = ["academic_year", "semester"]

src/university/views/v_academic_year.py
from typing import Any
from django.views import generic
from django.urls import reverse_lazy

from ..models import AcademicYear
from ..forms import AcademicYearForm


class AcademicYearsListCreateView(generic.ListView, generic.CreateView):
    template_name = "university/academic-years.html"
    form_class = AcademicYearForm
    success_url = reverse_lazy("university:academic_years:list")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return {"academic_years": self.get_queryset(), "form": self.form_class}

    def get_queryset(self):
        return AcademicYear.objects.all()

src/university/views/v_intake_class.py
from typing import Any
from django.views import generic
from django.urls import reverse_lazy

from ..models import IntakeClass
from ..forms import IntakeClassForm


class IntakeClassesListCreateView(generic.ListView, generic.CreateView):
    template_name = "university/intake-classes.html"
    form_class = IntakeClassForm
    success_url = reverse_lazy("university:intake_classes:list")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return {"intake_classes": self.get_queryset(), "form": self.form_class}

    def get_queryset(self):
        return IntakeClass.objects.all()


class IntakeClassDetailUpdateDeleteView(
    generic.DetailView, generic.UpdateView, generic.DeleteView
):
    template_name = "university/intake-class-detail.html"
    form_class = IntakeClassForm
    context_object_name = "intake_class"
    pk_url_kwarg = "class_pk"
    queryset = IntakeClass.objects.all()

    # def get_context_data(self, **kwargs) -> dict[str, Any]:
    #     context = super().get_context_data(**kwargs)
    #     context["streams"] =
    #     return context

src/university/views/v_intake_stream.py
from typing import Any
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from shared.utils import ListCreateView

from ..models import IntakeStream, IntakeClass
from ..forms import IntakeStreamForm


class IntakeStreamsListCreateView(ListCreateView):
    """Return streams that belong to a particular `IntakeClass`"""

    template_name = "university/intake-streams.html"
    form_class = IntakeStreamForm
    context_object_name = "intake_streams"

    def get_queryset(self):
        return IntakeStream.objects.filter(intake_class__exact=self.get_intake_class())

    def get_success_url(self):
        return reverse_lazy(
            "university:intake_classes:streams:list",
            kwargs={"class_pk": self.get_intake_class().pk},
        )

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["intake_class"] = self.get_intake_class()
        return context

    def get_intake_class(self) -> IntakeClass or Http404:
        return get_object_or_404(IntakeClass, pk__exact=self.kwargs.get("class_pk"))

    def form_valid(self, form):
        stream: IntakeStream = form.save(commit=False)
        stream.intake_class = self.get_intake_class()
        stream.save()
        return super().form_valid(form)


class IntakeStreamDetailUpdateView(generic.DetailView, generic.UpdateView):
    template_name = "university/intake_stream_detail.html"
    form_class = IntakeStreamForm
    pk_url_kwarg = "stream_pk"
    queryset = IntakeStream.objects.all()
    context_object_name = "stream"


class IntakeStreamDeleteView(generic.DeleteView):
    template_name = "university/intake_stream_delete.html"
    pk_url_kwarg = "stream_pk"
    queryset = IntakeStream.objects.all()
    context_object_name = "stream"

    def get_success_url(self):
        return reverse_lazy(
            "university:intake_classes:streams:list",
            kwargs={"class_pk": self.get_object().intake_class.pk},
        )

src/university/views/v_lecturer.py
from django.urls import reverse_lazy
from django.views import generic
from shared.utils import ListCreateView
from ..models import Lecturer
from ..forms import LecturerForm


class LecturersListCreateView(ListCreateView):
    template_name = "university/lecturers.html"
    form_class = LecturerForm
    success_url = reverse_lazy("university:lecturers:list")
    context_object_name = "lecturers"

    def get_queryset(self):
        return Lecturer.objects.all()


class LecturerDetailUpdateView(generic.UpdateView, generic.DetailView):
    form_class = LecturerForm
    queryset = Lecturer.objects.all()
    template_name = "university/lecturer_detail.html"


class LecturerDeleteView(generic.DeleteView):
    template_name = "university/lecturer_delete.html"
    queryset = Lecturer.objects.all()
    success_url = reverse_lazy("university:lecturers:list")

src/university/views/v_module.py
from django.urls import reverse_lazy
from django.views import generic
from shared.utils import ListCreateView
from ..models import Module
from ..forms import ModuleForm


class ModulesListCreateView(ListCreateView):
    template_name = "university/modules.html"
    form_class = ModuleForm
    success_url = reverse_lazy("university:modules:list")
    context_object_name = "modules"

    def get_queryset(self):
        return Module.objects.all()


class ModuleDetailUpdateDelete(
    generic.UpdateView, generic.DetailView, generic.DeleteView
):
    form_class = ModuleForm
    queryset = Module.objects.all()
    template_name = "university/module-detail.html"

src/university/views/v_session.py
from django.views import generic
from django.http import HttpResponse
from django.forms.models import BaseModelForm
from django.urls import reverse_lazy

from ..forms import SessionForm
from ..models import Session
from ..utils import get_timetable


class SessionAddView(generic.CreateView):
    """Allows adding of a session to a specific visited timetable item. Timetable `pk` must be supplied in the url
    via `timetable_pk` kwarg
    """

    form_class = SessionForm

    def get_queryset(self):
        return Session.objects.filter(timetable__exact=get_timetable(view=self))

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        instance = form.save(commit=False)
        timetable = get_timetable(view=self)
        if timetable:
            instance.timetable = timetable
            instance.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy(
            "university:timetables:detail",
            kwargs={"timetable_pk": self.kwargs.get("timetable_pk")},
        )

src/university/views/v_timetable.py
from typing import Any
from django.forms.models import BaseModelForm
from django.views import generic
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from general.models import WeekDay
from ..models import *
from ..forms import TimetableForm, SessionForm
from ..utils import get_stream


class CreateTimetableView(generic.CreateView):
    template_name = "university/timetable/add_timetable.html"
    form_class = TimetableForm
    queryset = Timetable.objects.all()

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        instance: Timetable = form.save(commit=False)
        instance.intake_stream = get_stream(view=self)
        instance.save()
        return super().form_valid(form)

    def get_success_url(self):
        stream = get_stream(view=self)
        return reverse_lazy(
            "university:intake_classes:streams:detail",
            kwargs={"class_pk": stream.intake_class.pk, "stream_pk": stream.pk},
        )

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["stream"] = get_stream(view=self)
        return context


class StreamTimetablesListView(generic.ListView):
    template_name = "university/stream_timetables.html"

    def get_queryset(self):
        return Timetable.objects.filter(intake_stream__exact=get_stream(view=self))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["stream"] = get_stream(view=self)
        return context


class TimetableDetailUpdateView(generic.UpdateView, generic.DetailView):
    form_class = TimetableForm
    template_name = "university/timetable/timetable_detail.html"
    pk_url_kwarg = "timetable_pk"
    queryset = Timetable.objects.all()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["sessions"] = self.get_sessions()
        context["week_days"] = WeekDay.objects.all()
        context["session_form"] = SessionForm
        return context

    def get_sessions(self):
        return Session.objects.filter(timetable__exact=self.get_object())


class AcademicYearSelectionView(generic.ListView):
    template_name = "university/timetable/academic_year_selection.html"

    def get_queryset(self):
        return AcademicYear.objects.all()


class IntakeClassSelectionView(generic.ListView):
    template_name = "university/timetable/intake_class_selection.html"

    def get_queryset(self):
        return IntakeClass.objects.filter(academic_year=self.get_academic_year())

    def get_academic_year(self) -> AcademicYear or Http404:
        return get_object_or_404(AcademicYear, pk__exact=self.kwargs.get("acyear_pk"))


class IntakeStreamSelectionView(generic.ListView):
    template_name = "university/timetable/stream_selection.html"

    def get_queryset(self):
        return IntakeStream.objects.filter(intake_class__exact=self.get_intake_class())

    def get_intake_class(self) -> IntakeClass or Http404:
        return get_object_or_404(IntakeClass, pk__exact=self.kwargs.get("class_pk"))


class StreamTimetableView(generic.ListView):
    template_name = "university/timetable/stream_timetable.html"

    def get_queryset(self):
        return Timetable.objects.filter(intake_stream__exact=get_stream(view=self))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["week_days"] = WeekDay.objects.all()
        context["sessions"] = self.get_sessions()
        return context

    def get_sessions(self):
        sessions = Session.objects.filter(timetable__in=self.get_queryset())
        return sessions

src/templates/university/academic-years.html
{% extends "../base/base.html" %}

{% block title %}Academic Years{% endblock title %}

{% block content_outlet %}

<div class="d-flex justify-content-between align-items-center">
    <h3>Academic Years</h3>
    <button class="btn btn-primary btn-sm" type="button" aria-label="Add" data-bs-toggle="modal" data-bs-target="#add-academic-yr-modal">Add Academic Year</button>
</div>


<!-- table -->
<div class="table-container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
            {% for academic_year in academic_years %}
            <tr>
                <td> {{ academic_year.id }} </td>
                <td> {{ academic_year.name }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- add modal -->
<div class="modal fade" id="add-academic-yr-modal" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="post">

                {% include "../base/modal-header.html" %}

                <div class="modal-body">

                    <div class="form-section">
                        <table class="table table-borderless">
                            <tbody>
                                {% csrf_token %}

                                {{ form.as_table }}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    {% include "../base/form-btns.html" %}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/academic_years.html
{% extends "../base/base.html" %}

{% block title %}Academic Years{% endblock title %}

{% block content_outlet %}

<div class="d-flex justify-content-between align-items-center">
    <h3>Academic Years</h3>
    <button class="btn btn-primary btn-sm" type="button" aria-label="Add" data-bs-toggle="modal" data-bs-target="#add-academic-yr-modal">Add Academic Year</button>
</div>


<!-- table -->
<div class="table-container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
        </thead>

        <tbody>
            {% for academic_year in academic_years %}
            <tr>
                <td> {{ academic_year.id }} </td>
                <td> {{ academic_year.name }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- add modal -->
<div class="modal fade" id="add-academic-yr-modal" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="post">

                {% include "../base/modal-header.html" %}

                <div class="modal-body">

                    <div class="form-section">
                        <table class="table table-borderless">
                            <tbody>
                                {% csrf_token %}

                                {{ form.as_table }}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    {% include "../base/form-btns.html" %}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/intake-class-detail.html
{% extends "../base/base.html" %}

{% block title %}Intake class{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h3 class="alert alert-secondary border-bottom border-dark-subtle rounded-0"> Intake class: {{ intake_class.class_code }} </h3>

            <form action="" method="post" class="form-section">
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            {{ form.as_table }}
                        </tbody>
                    </table>
                </div>

                {% include "../base/form-btns.html" %}
            </form>
        </div>
    <div class="col-md-4 col-12">
        <h4>Actions&colon;</h4>

        <div class="actions-container">
            <button class="btn btn-danger btn-md">Delete</button>

            <div class="mt-4">
                <h6>Available streams</h6>
                    <div class="table-responsive">
                    <table class="table table-striped">
                         <tbody>
                            {% for stream in intake_class.streams.all %}

                            <tr>
                                <td> 
                                    <a href="{{ stream.get_absolute_url }}">{{ stream.stream_code }}</a>
                                </td>
                            </tr>
                            
                            {% endfor %}
                        </tbody>
                    </table>
                </div> 

                <a href="{% url 'university:intake_classes:streams:list' class_pk=intake_class.pk %}" class="mt-4 text-decoration-none">View all streams</a>

            </div>
        </div>
    </div>
</div>



{% endblock content_outlet %}

src/templates/university/intake-classes.html
{% extends "../base/base.html" %}

{% block title %}Intake classes{% endblock title %}

{% block content_outlet %}

<div class="d-flex justify-content-between align-items-center">
    <h3>Intake classes</h3>
    <button class="btn btn-primary btn-sm" type="button" aria-label="Add" data-bs-toggle="modal" data-bs-target="#add-intake-class-modal">Add Intake</button>
</div>


<!-- table -->
<div class="table-container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Class Code</th>
                <th>Academic Yr</th>
            </tr>
        </thead>

        <tbody>
            {% for intake_class in intake_classes %}
            <tr>
                <td> {{ intake_class.class_code }} </td>
                <td> {{ intake_class.academic_year.name }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- add modal -->
<div class="modal fade" id="add-intake-class-modal" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="post">

                {% include "../base/modal-header.html" %}

                <div class="modal-body">

                    <div class="form-section">
                        <table class="table table-borderless">
                            <tbody>
                                {% csrf_token %}

                                {{ form.as_table }}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    {% include "../base/form-btns.html" %}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/intake-streams.html
{% extends "../base/base.html" %}

{% block title %}Intake streams{% endblock title %}

{% block content_outlet %}

<div class="d-flex justify-content-between align-items-center border-bottom my-3">
    <h3>Streams of {{ intake_class.class_code }} </h3>
    <button class="btn btn-primary btn-sm" type="button" aria-label="Add" data-bs-toggle="modal" data-bs-target="#add-intake-class-modal">Add Stream</button>
</div>


<!-- table -->
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Intake stream code</th>
            </tr>
        </thead>

        <tbody>
            {% for stream in intake_streams %}
            <tr>
                <td> <a href="{{ stream.get_absolute_url }}">{{ stream.stream_code }}</a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- add modal -->
<div class="modal fade" id="add-intake-class-modal" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="" method="post">

                {% include "../base/modal-header.html" %}

                <div class="modal-body">

                    <div class="form-section">
                        <table class="table table-borderless">
                            <tbody>
                                {% csrf_token %}

                                {{ form.as_table }}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    {% include "../base/form-btns.html" %}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/intake_stream_delete.html
{% extends "../base/base.html" %}

{% block title %}Intake stream{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h4 class="alert alert-secondary border-bottom border-dark-subtle rounded-0 fw-light"> Want to delete stream?</h4>

            <blockquote>This object might have related objects</blockquote>

            <form action="" method="post" class="form-section">
                {% csrf_token %}

                <input class="btn btn-danger btn-sm" type="submit" value="Yes, Delete" />
                <a href="{{ stream.get_absolute_url }}" class="btn btn-warning btn-sm">No, Cancel</a>
            </form>
        </div>
</div>

{% endblock content_outlet %}

src/templates/university/intake_stream_detail.html
{% extends "../base/base.html" %}

{% block title %}Intake stream{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h3 class="alert alert-secondary border-bottom border-dark-subtle rounded-0"> Intake stream detail</h3>

            <form action="" method="post" class="form-section">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            {{ form.as_table }}
                        </tbody>
                    </table>
                </div>

                {% include "../base/form-btns.html" %}
            </form>
        </div>
    <div class="col-md-4 col-12">
        <h4>Actions&colon;</h4>

        <div class="actions-container d-flex gap-3 flex-row">
            <a href="{% url 'university:intake_classes:streams:delete' class_pk=stream.intake_class.pk stream_pk=stream.pk %}" class="btn btn-danger btn-sm">Delete</a>

            {% if stream.timetable_set.count < 1 %}

            <a href="{% url 'university:timetables:add_timetable' stream.pk %}" class="btn btn-sm btn-primary">Add timetable</a>

            {% else %}

            <a href="{% url 'university:timetables:list' stream.pk %}" class="btn btn-primary btn-sm">View timetables</a>
            
            {% endif %}
        </div>            
                
                            
        </form>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/lecturer-detail.html
{% extends "../base/base.html" %}

{% block title %}Lecturer{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h3 class="alert alert-secondary border-bottom border-dark-subtle rounded-0"> Lecturer detail</h3>

            <form action="" method="post" class="form-section" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            {{ form.as_table }}
                        </tbody>
                    </table>
                </div>

                {% include "../base/form-btns.html" %}
            </form>
        </div>
    <div class="col-md-4 col-12">
        <h4>Actions&colon;</h4>

        <div class="actions-container">
            <button class="btn btn-danger btn-md">Delete</button>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/lecturer_delete.html
{% extends "../base/base.html" %}

{% block title %}Delete Lecturer{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h4 class="alert alert-secondary border-bottom border-dark-subtle rounded-0 fw-light"> Want to delete a Lecturer?</h4>

            <blockquote>This object might have other related objects</blockquote>

            <form action="" method="post" class="form-section">
                {% csrf_token %}

                <input class="btn btn-danger btn-sm" type="submit" value="Yes, Delete" />
                <a href="{{ object.get_absolute_url }}" class="btn btn-warning btn-sm">No, Cancel</a>
            </form>
        </div>
</div>

{% endblock content_outlet %}

src/templates/university/module-detail.html
{% extends "../base/base.html" %}

{% block title %}Module{% endblock title %}

{% block content_outlet %}


<div class="row row-cols-md-2 row-cols-1">
    <div class="col-md-8 col-12">
        <h3 class="alert alert-secondary border-bottom border-dark-subtle rounded-0"> Module detail</h3>

            <form action="" method="post" class="form-section">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                            {{ form.as_table }}
                        </tbody>
                    </table>
                </div>

                {% include "../base/form-btns.html" %}
            </form>
        </div>
    <div class="col-md-4 col-12">
        <h4>Actions&colon;</h4>

        <div class="actions-container">
            <button class="btn btn-danger btn-md">Delete</button>
        </div>
    </div>
</div>

{% endblock content_outlet %}

src/templates/university/timetable.html
{% extends "../base/base.html" %}

{% block title %}Timetable{% endblock title %}

{% block content_outlet %}

<ul>
  {% for timetable_record in timetables %}

  <li>{{ timetable_record }}</li>
  {% endfor %}
</ul>

{% endblock content_outlet %}